export const ROUTES = {
  LOGIN:               '/login',
  FORGOT_PASSWORD:     '/forgot-password',
  RESET_PASSWORD:      '/reset-password',
  MONITORING:          '/monitoring',
  ANALYTICS:           '/analytics',
  ALERTS:              '/alerts',
  WORKERS:             '/workers',
  WORKER_PROFILE:      (id: string) => `/workers/${id}`,
  REPORTS:             '/reports',
  REPORTS_ANALYTICS:   '/reports/analytics',
  KPI:                 '/kpi',
  PROFILE:             '/profile',
  HELP:                '/help',
  ADMIN:               '/admin',
  ADMIN_USERS:         '/admin/users',
  ADMIN_ZONES:         '/admin/zones',
  ADMIN_CAMERAS:       '/admin/cameras',
  ADMIN_ALERT_CONFIG:  '/admin/alert-config',
  ADMIN_SYSTEM_HEALTH: '/admin/system-health',
  ADMIN_AUDIT_LOG:     '/admin/audit-log',
  FORBIDDEN:           '/forbidden',
} as const;
